#pragma once


#define	CB_WD_EVENT_NONE					SDL_WINDOWEVENT_NONE
#define	CB_WD_EVENT_SHOWN					SDL_WINDOWEVENT_SHOWN
#define	CB_WD_EVENT_HIDDEN					SDL_WINDOWEVENT_HIDDEN
#define	CB_WD_EVENT_MOVED					SDL_WINDOWEVENT_MOVED
#define	CB_WD_EVENT_RESIZED					SDL_WINDOWEVENT_RESIZED
#define	CB_WD_EVENT_SIZE_CHANGED			SDL_WINDOWEVENT_SIZE_CHANGED
#define	CB_WD_EVENT_MINIMIZED				SDL_WINDOWEVENT_MINIMIZED
#define	CB_WD_EVENT_MAXIMIZED				SDL_WINDOWEVENT_MAXIMIZED
#define	CB_WD_EVENT_RESTORED				SDL_WINDOWEVENT_RESTORED
#define	CB_WD_EVENT_ENTER					SDL_WINDOWEVENT_ENTER
#define	CB_WD_EVENT_LEAVE					SDL_WINDOWEVENT_LEAVE
#define	CB_WD_EVENT_FOCUS_GAINED			SDL_WINDOWEVENT_FOCUS_GAINED
#define	CB_WD_EVENT_FOCUS_LOST				SDL_WINDOWEVENT_FOCUS_LOST
#define	CB_WD_EVENT_CLOSE					SDL_WINDOWEVENT_CLOSE
#define	CB_WD_EVENT_TAKE_FOCUS				SDL_WINDOWEVENT_TAKE_FOCUS
#define	CB_WD_EVENT_HIT_TEST  				SDL_WINDOWEVENT_HIT_TEST